# Uncomment the next line to define a global platform for your project
platform :ios, '17.2'

target 'TestingWithBank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestingWithBank

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  target 'TestingWithBankTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestingWithBankUITests' do
    # Pods for testing
  end

end
